package dashboard;
import java.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author James Nathanael
 */
public class FrmBarang extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.koneksi.getKoneksi();
    
    public FrmBarang() {
        initComponents();
        reset();
        judul();
        tampilData();
        tampilcombo();
        kode();
        TxtKdBarang.setEnabled(false);
    }
    public void judul(){
        Object[] judul = {"Kode Barang", "Nama Barang","Jenis Barang",
            "Harga Beli","Harga Jual", "Stok",};
        tabModel = new DefaultTableModel(null,judul);
        TblBarang.setModel(tabModel);
    }
    public void tampilData(){
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tb_barang");
            while(rs.next()){
                Object[] data = {
                    rs.getString("kd_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("jenis_barang"),
                    rs.getString("harga_beli"),
                    rs.getString("harga_jual"),
                    rs.getString("stok_barang")
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void reset(){
        TxtKdBarang.setText("");
        TxtNmBarang.setText("");
        TxtHargaBeli.setText("");
        TxtHargaJual.setText("");
        TxtStok.setText("");
        CbBarang.setSelectedItem("-Pilih Jenis-");
        kode();
        BtnSimpan.setEnabled(true);
        BtnUpdate.setEnabled(false);
        BtnDelete.setEnabled(false);
    }
    public void tampilcombo(){
        CbBarang.removeAllItems();
        CbBarang.addItem("-Pilih Jenis-");
        CbBarang.addItem("Makanan");
        CbBarang.addItem("Minuman");
        CbBarang.addItem("Alat");
    }
    public void kode(){
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_barang "
                    + "order by kd_barang DESC");
            if(rs.next()){
                String kd = rs.getString("kd_barang").substring(1);
                String kode = "000" + (Integer.parseInt(kd)+1);
                TxtKdBarang.setText("B"+kode);
            }else{
                TxtKdBarang.setText("B0001");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal"+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblBarang = new javax.swing.JTable();
        CbBarang = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        TxtKdBarang = new javax.swing.JTextField();
        TxtPencarian = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        TxtHargaBeli = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        TxtHargaJual = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        TxtNmBarang = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        BtnSimpan = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        TxtStok = new javax.swing.JTextField();
        BtnKembali = new javax.swing.JButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setText("Form Data Barang");

        TblBarang.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TblBarang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Barang", "Nama Barang", "Harga Beli", "Harga Jual", "Stok"
            }
        ));
        TblBarang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblBarangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblBarang);

        CbBarang.setFont(new java.awt.Font("Century Gothic", 0, 11)); // NOI18N
        CbBarang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Harga Beli");

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Pencarian");

        TxtKdBarang.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        TxtPencarian.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TxtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPencarianKeyReleased(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Harga Jual");

        TxtHargaBeli.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Kode Barang");

        TxtHargaJual.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Nama Barang");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Stok Barang");

        TxtNmBarang.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Jenis Barang");

        BtnSimpan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnBatal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnBatal.setText("Batal");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        TxtStok.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        BtnKembali.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnKembali.setText("Kembali");
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        BtnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel4))
                        .addGap(49, 280, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(BtnSimpan)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnUpdate)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(BtnBatal))
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(TxtNmBarang, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CbBarang, javax.swing.GroupLayout.Alignment.LEADING, 0, 209, Short.MAX_VALUE)
                                    .addComponent(TxtHargaJual, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtHargaBeli, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtKdBarang)
                                    .addComponent(TxtStok))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addGap(31, 31, 31)
                        .addComponent(TxtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(BtnKembali, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(TxtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtKdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtNmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(CbBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtHargaBeli, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(TxtHargaJual, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxtStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnBatal)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnDelete)
                    .addComponent(BtnKembali))
                .addGap(46, 46, 46))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
        dashboard.FrmDashboard k = new dashboard.FrmDashboard();
        k.setVisible(true);
        this.setVisible(false);       
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("insert into tb_barang set "
                    + "kd_barang='"+ TxtKdBarang.getText() +"',"
                    + "nama_barang='" + TxtNmBarang.getText() + "'," 
                    + "jenis_barang='" +CbBarang.getSelectedItem() +"'," 
                    + "harga_beli = '"+TxtHargaBeli.getText()+"',"
                    + "harga_jual = '"+TxtHargaJual.getText()+"',"
                    + "stok_barang='" + TxtStok.getText() + "'");
            tampilData();
            reset();
            JOptionPane.showMessageDialog(null,"Berhasil Menambah Data!");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        reset();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void TxtPencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPencarianKeyReleased
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("Select * from tb_barang where "
                    + "kd_barang like '%"+ TxtPencarian.getText() +"%'"
                    + " or nama_barang like '%"+ TxtPencarian.getText() +"%' "
                    + "or jenis_barang like '%"+ TxtPencarian.getText() +"%' "
                    + "or stok_barang like '%"+ TxtPencarian.getText() +"%'");
            while(rs.next()){
                Object[] data = {
                    rs.getString("kd_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("jenis_barang"),
                    rs.getString("harga_beli"),
                    rs.getString("harga_jual"),
                    rs.getString("stok_barang")     
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_TxtPencarianKeyReleased

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        try{
            st = cn.createStatement();
            st.executeUpdate("update tb_barang set " 
                    + "nama_barang='"+ TxtNmBarang.getText() + "',"
                    +"jenis_barang='" + CbBarang.getSelectedItem() + "',"
                    +"harga_beli='" + TxtHargaBeli.getText() + "',"
                    +"harga_jual='" + TxtHargaJual.getText() + "',"
                    +"stok_barang='" + TxtStok.getText() + "' "
                    +"where kd_barang='"+ 
                    tabModel.getValueAt(TblBarang.getSelectedRow(),0)+"';");
            tampilData();
            reset();
            JOptionPane.showMessageDialog(null,"Berhasil Mengupdate Data!!");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        try{
        int jawab;
        if((jawab= JOptionPane.showConfirmDialog(null,"Ingin Menghapus?",
            "Konfirmasi",JOptionPane.YES_NO_OPTION))==0){
            st = cn.createStatement();
            st.executeUpdate("delete from tb_barang where "
                    + "kd_barang='"+ 
                    tabModel.getValueAt(TblBarang.getSelectedRow(),0)+"'");
            tampilData();
            reset();  
            JOptionPane.showMessageDialog(null,"Data Telah Terhapus!!");
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void TblBarangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblBarangMouseClicked
        // TODO add your handling code here:
        TxtKdBarang.setText(tabModel.getValueAt(TblBarang.getSelectedRow(), 0)+ "");
        TxtNmBarang.setText(tabModel.getValueAt(TblBarang.getSelectedRow(), 1)+ "");
        CbBarang.setSelectedItem(tabModel.getValueAt(TblBarang.getSelectedRow(), 2)+ "");
        TxtHargaBeli.setText(tabModel.getValueAt(TblBarang.getSelectedRow(), 3)+ "");
        TxtHargaJual.setText(tabModel.getValueAt(TblBarang.getSelectedRow(), 4)+ "");
        TxtStok.setText(tabModel.getValueAt(TblBarang.getSelectedRow(), 5)+ "");
        
        BtnSimpan.setEnabled(false);
        BtnUpdate.setEnabled(true);
        BtnDelete.setEnabled(true);
    }//GEN-LAST:event_TblBarangMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmBarang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmBarang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox<String> CbBarang;
    private javax.swing.JTable TblBarang;
    private javax.swing.JTextField TxtHargaBeli;
    private javax.swing.JTextField TxtHargaJual;
    private javax.swing.JTextField TxtKdBarang;
    private javax.swing.JTextField TxtNmBarang;
    private javax.swing.JTextField TxtPencarian;
    private javax.swing.JTextField TxtStok;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
