/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;
import java.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Set;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author James Nathanael
 */
public class FrmPasok extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.koneksi.getKoneksi();
    /**
     * Creates new form FrmPasok
     */
    public FrmPasok() {
        initComponents();
        judul();
        tampilData();
        reset();
        tampilCombo();
        kode();
        TxtNmBarang.setEnabled(false);
        TxtKdPasok.setEnabled(false);
        TxtNmBarang.setText("");
        TxtKdPemasok.setEnabled(false); 
       
    }
    
    public void judul(){
        Object[] judul = {"Kode Pasok", "Kode barang", "Nama Barang","Jumlah", "Tanggal Masuk", "Kode Pemasok","Pemasok",};
        tabModel = new DefaultTableModel(null,judul);
        TblPasok.setModel(tabModel);
    }
    public void tampilData(){
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tb_pasok order by tgl_masuk asc");
            while(rs.next()){
                Object[] data = {
                    rs.getString("kd_pasok"),
                    rs.getString("kd_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("jumlah"),
                    rs.getString("tgl_masuk"),
                    rs.getString("kd_pemasok"),
                    rs.getString("pemasok")
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }

    public void reset(){
        TxtKdPasok.setText("");
        TxtKdBarang.setText("");
        TxtNmBarang.setText("");
        TxtJumlah.setText("");
        kode();
        BtnSimpan.setEnabled(true);
        BtnDelete.setEnabled(false);
        BtnUpdate.setEnabled(false);
        TxtPemasok.setSelectedIndex(0);
    }
    public void tampilCombo(){
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_pemasok");
            
            while(rs.next())
            {
               TxtPemasok.addItem(rs.getString("nama_pemasok"));
            }
        }catch(Exception e){
           e.printStackTrace();
        }
        
    }
    public void kode(){
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_pasok order by kd_pasok DESC");
            if(rs.next()){
                String kd = rs.getString("kd_pasok").substring(1);
                String kode = "000" + (Integer.parseInt(kd)+1);
                TxtKdPasok.setText("P"+kode);
            }else{
                TxtKdPasok.setText("P0001");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal"+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtNmBarang = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        TxtKdBarang = new javax.swing.JTextField();
        BtnSimpan = new javax.swing.JButton();
        TxtPencarian = new javax.swing.JTextField();
        BtnBatal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtJumlah = new javax.swing.JTextField();
        TxtKdPasok = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPasok = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        Kembali = new javax.swing.JButton();
        TxtPemasok = new javax.swing.JComboBox<>();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        BtnCetak = new javax.swing.JButton();
        TxtKdPemasok = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        TglMasuk = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Kode Pasok");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Tanggal Masuk");

        TxtNmBarang.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TxtNmBarang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtNmBarangActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Pencarian");

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Jumlah");

        TxtKdBarang.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TxtKdBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtKdBarangKeyReleased(evt);
            }
        });

        BtnSimpan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        TxtPencarian.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TxtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPencarianKeyReleased(evt);
            }
        });

        BtnBatal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnBatal.setText("Batal");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Pemasok");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setText("Form Pasokan");

        TxtJumlah.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        TxtKdPasok.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Kode Barang");

        TblPasok.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TblPasok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Pasok", "Kode Barang", "Nama Barang", "Jumlah", "Tanggal Masuk"
            }
        ));
        TblPasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPasokMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblPasok);
        if (TblPasok.getColumnModel().getColumnCount() > 0) {
            TblPasok.getColumnModel().getColumn(4).setHeaderValue("Tanggal Masuk");
        }

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Nama Barang");

        Kembali.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        TxtPemasok.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TxtPemasok.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "-Pilih Pemasok-" }));
        TxtPemasok.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                TxtPemasokItemStateChanged(evt);
            }
        });
        TxtPemasok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TxtPemasokMouseClicked(evt);
            }
        });
        TxtPemasok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtPemasokActionPerformed(evt);
            }
        });
        TxtPemasok.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                TxtPemasokPropertyChange(evt);
            }
        });

        BtnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        BtnCetak.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnCetak.setText("CETAK");
        BtnCetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCetakActionPerformed(evt);
            }
        });

        TxtKdPemasok.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Kode Pemasok");

        TglMasuk.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(21, 21, 21)
                                .addComponent(TxtKdPemasok))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(166, 203, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3)
                                                .addComponent(jLabel2)
                                                .addComponent(jLabel8))
                                            .addGap(9, 9, 9))
                                        .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                                    .addComponent(jLabel7))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(TxtPemasok, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TglMasuk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtJumlah)
                                    .addComponent(TxtNmBarang)
                                    .addComponent(TxtKdBarang)
                                    .addComponent(TxtKdPasok))))
                        .addGap(43, 43, 43)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(18, 18, 18)
                                .addComponent(TxtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 337, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(BtnCetak)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Kembali, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(27, 27, 27))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSimpan)
                        .addGap(2, 2, 2)
                        .addComponent(BtnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(BtnDelete)
                        .addGap(14, 14, 14)
                        .addComponent(BtnBatal)
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel9)
                    .addComponent(TxtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxtKdPasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtKdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtNmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(TxtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel6))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(TglMasuk, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(13, 13, 13))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(TxtKdPemasok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BtnCetak))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnDelete)
                    .addComponent(BtnBatal)
                    .addComponent(Kembali))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
        dashboard.FrmDashboard k = new dashboard.FrmDashboard();
        k.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_KembaliActionPerformed

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:
        if(TxtNmBarang.getText().equals("")){
            JOptionPane.showMessageDialog(null,"Tidak Ada Kode Barang Tersebut!");
        }else{
            try{
                String tgl = ((JTextField)TglMasuk.getDateEditor().getUiComponent()).getText();
                st = cn.createStatement();
                st.executeUpdate("insert into tb_pasok set "+ "kd_pasok='"+ TxtKdPasok.getText() +"',"
                        + "kd_barang='" + TxtKdBarang.getText() + "'," 
                        + "nama_barang='" +TxtNmBarang.getText() +"'," 
                        + "jumlah = '"+TxtJumlah.getText()+"',"
                        + "tgl_masuk = '"+tgl+"',"
                        + "kd_pemasok = '"+TxtKdPemasok.getText()+"',"
                        + "pemasok='" + TxtPemasok.getSelectedItem() + "'");
                tampilData();
                reset();
                JOptionPane.showMessageDialog(null,"Berhasil Menambah Data!");
            }catch(Exception e){
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void TxtKdBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKdBarangKeyReleased
        // TODO add your handling code here:
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_barang WHERE kd_barang = '"+TxtKdBarang.getText()+"'");
            if(rs.next()){
              if( TxtKdBarang.getText().equals(rs.getString("kd_barang"))){
                  TxtNmBarang.setText(rs.getString("nama_barang"));
              }
            }else{
                TxtNmBarang.setText("");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal"+e.getMessage());
        }
    }//GEN-LAST:event_TxtKdBarangKeyReleased

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void TxtPencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPencarianKeyReleased
        // TODO add your handling code here:
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("Select * from tb_pasok where kd_barang like '%"+ TxtPencarian.getText() +"%'"
                    + " or nama_barang like '%"+ TxtPencarian.getText() +"%' "
                    + "or kd_pasok like '%"+ TxtPencarian.getText() +"%' "
                    + "or pemasok like '%"+ TxtPencarian.getText() +"%' "
                    + "or tgl_masuk like '%"+ TxtPencarian.getText() +"%'");
            while(rs.next()){
                Object[] data = {
                    rs.getString("kd_pasok"),
                    rs.getString("kd_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("jumlah"),
                    rs.getString("tgl_masuk"),
                    rs.getString("pemasok")    
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_TxtPencarianKeyReleased

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        try{
            String tgl = ((JTextField)TglMasuk.getDateEditor().getUiComponent()).getText();
            st = cn.createStatement();
            st.executeUpdate("update tb_pasok set " + "kd_barang='"+ TxtKdBarang.getText() + "',"
                +"nama_barang='" + TxtNmBarang.getText() + "',"
                +"jumlah='" + TxtJumlah.getText() + "',"
                +"tgl_masuk='" + tgl + "',"
                +"kd_pemasok='" + TxtKdPemasok.getText() + "',"
                +"pemasok='" + TxtPemasok.getSelectedItem() + "' "
                +"where kd_pasok='"+ tabModel.getValueAt(TblPasok.getSelectedRow(),0)+"';");
            tampilData();
            reset();
            JOptionPane.showMessageDialog(null,"Berhasil Mengupdate Data!!");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            int jawab;
            if((jawab= JOptionPane.showConfirmDialog(null,"Ingin Menghapus?",
                "Konfirmasi",JOptionPane.YES_NO_OPTION))==0){
        st = cn.createStatement();
        st.executeUpdate("delete from tb_pasok where "
            + "kd_pasok='"+ tabModel.getValueAt(TblPasok.getSelectedRow(),0)+"'");
        tampilData();
        reset();
        JOptionPane.showMessageDialog(null,"Data Telah Terhapus!!");
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void TblPasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPasokMouseClicked
        // TODO add your handling code here:
        TxtKdPasok.setText(tabModel.getValueAt(TblPasok.getSelectedRow(), 0)+ "");
        TxtKdBarang.setText(tabModel.getValueAt(TblPasok.getSelectedRow(), 1)+ "");
        TxtNmBarang.setText(tabModel.getValueAt(TblPasok.getSelectedRow(), 2)+ "");
        TxtJumlah.setText(tabModel.getValueAt(TblPasok.getSelectedRow(), 3)+ "");
        TglMasuk.setDateFormatString(tabModel.getValueAt(TblPasok.getSelectedRow(), 4)+ "");
        TxtKdPemasok.setText(tabModel.getValueAt(TblPasok.getSelectedRow(),5)+"");
        TxtPemasok.setSelectedItem(tabModel.getValueAt(TblPasok.getSelectedRow(), 6)+ "");
 
        BtnSimpan.setEnabled(false);
        BtnUpdate.setEnabled(true);
        BtnDelete.setEnabled(true);
    }//GEN-LAST:event_TblPasokMouseClicked

    private void TxtNmBarangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtNmBarangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtNmBarangActionPerformed

    private void BtnCetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCetakActionPerformed
        // TODO add your handling code here:
        FrmPopUp k = new FrmPopUp();
        k.setVisible(true);
        
    }//GEN-LAST:event_BtnCetakActionPerformed

    private void TxtPemasokItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_TxtPemasokItemStateChanged
        // TODO add your handling code here: 
    }//GEN-LAST:event_TxtPemasokItemStateChanged

    private void TxtPemasokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TxtPemasokMouseClicked
        // TODO add your handling code here:       
        
    }//GEN-LAST:event_TxtPemasokMouseClicked

    private void TxtPemasokPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_TxtPemasokPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtPemasokPropertyChange

    private void TxtPemasokActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtPemasokActionPerformed
        // TODO add your handling code here:   
        try{
            rs = st.executeQuery("SELECT * FROM tb_pemasok WHERE nama_pemasok = '"+TxtPemasok.getSelectedItem()+"'");
            if(rs.next()){          
                  TxtKdPemasok.setText(rs.getString("kd_pemasok"));             
            }else{
                TxtKdPemasok.setText("");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal"+e.getMessage());
        }
    }//GEN-LAST:event_TxtPemasokActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPasok.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPasok().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnCetak;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JButton Kembali;
    private javax.swing.JTable TblPasok;
    private com.toedter.calendar.JDateChooser TglMasuk;
    private javax.swing.JTextField TxtJumlah;
    private javax.swing.JTextField TxtKdBarang;
    private javax.swing.JTextField TxtKdPasok;
    private javax.swing.JTextField TxtKdPemasok;
    private javax.swing.JTextField TxtNmBarang;
    private javax.swing.JComboBox<String> TxtPemasok;
    private javax.swing.JTextField TxtPencarian;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
