/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package dashboard;
import java.*;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author James Nathanael
 */
public class FrmPengguna extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Connection cn = koneksi.koneksi.getKoneksi();
    /**
     * Creates new form FrmPengguna
     */
    public FrmPengguna() {
        initComponents();
        judul();
        tampilData();
        tampilCombo();
        kode();
        TxtKdPengguna.setEnabled(false);
    }
    public void judul(){
        Object[] judul = {"Kode Pengguna", "Nama Pengguna", "Jenis Kelamin","Nomor HP", "Jabaran", "Username","Password",};
        tabModel = new DefaultTableModel(null,judul);
        TblPengguna.setModel(tabModel);
    }
    public void tampilData(){
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tb_user");
            while(rs.next()){
                Object[] data = {
                    rs.getString("kd_pengguna"),
                    rs.getString("nama_pengguna"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("no_hp"),
                    rs.getString("jabatan"),
                    rs.getString("username"),
                    rs.getString("password")
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void reset(){
        TxtKdPengguna.setText("");
        TxtNmPengguna.setText("");
        buttonGroup2.clearSelection();
        TxtHP.setText("");
        CbJabatan.setSelectedItem("Manager");
        TxtUsername.setText("");
        TxtPassword.setText("");
        TxtKdPengguna.requestFocus();
        kode();
        BtnSimpan.setEnabled(true);
        BtnUpdate.setEnabled(false);
        BtnDelete.setEnabled(false);
    }
    
    public void tampilCombo(){
        CbJabatan.removeAllItems();
        CbJabatan.addItem("Manager");
        CbJabatan.addItem("Admin");
        CbJabatan.addItem("Kasir");
    }
    
    public void kode(){
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_user order by kd_pengguna DESC");
            if(rs.next()){
                String kd = rs.getString("kd_pengguna").substring(2);
                String kode = "000" + (Integer.parseInt(kd)+1);
                TxtKdPengguna.setText("ID"+kode);
            }else{
                TxtKdPengguna.setText("ID0001");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal"+e.getMessage());
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        CbJabatan = new javax.swing.JComboBox<>();
        TxtKdPengguna = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TxtNmPengguna = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtHP = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        TxtUsername = new javax.swing.JTextField();
        TxtPassword = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        BtnSimpan = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblPengguna = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        TxtPencarian = new javax.swing.JTextField();
        Kembali = new javax.swing.JButton();
        RdLakiLaki = new javax.swing.JRadioButton();
        RdPerempuan = new javax.swing.JRadioButton();
        BtnUpdate = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setText("Form User");

        CbJabatan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        CbJabatan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        TxtKdPengguna.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Kode Pengguna");

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Nama Pengguna");

        TxtNmPengguna.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Jenis Kelamin");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Nomor HP");

        TxtHP.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Jabatan");

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Username");

        TxtUsername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        TxtPassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Password");

        BtnSimpan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnBatal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnBatal.setText("Batal");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        TblPengguna.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TblPengguna.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Kode Pengguna", "Nama Pengguna", "Username", "Password"
            }
        ));
        TblPengguna.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblPenggunaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblPengguna);

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Pencarian");

        TxtPencarian.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TxtPencarian.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtPencarianKeyReleased(evt);
            }
        });

        Kembali.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        Kembali.setText("Kembali");
        Kembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KembaliActionPerformed(evt);
            }
        });

        buttonGroup2.add(RdLakiLaki);
        RdLakiLaki.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        RdLakiLaki.setText("Laki-laki");

        buttonGroup2.add(RdPerempuan);
        RdPerempuan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        RdPerempuan.setText("Perempuan");

        BtnUpdate.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnUpdate.setText("Update");
        BtnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUpdateActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(BtnSimpan)
                        .addGap(14, 14, 14)
                        .addComponent(BtnUpdate)
                        .addGap(18, 18, 18)
                        .addComponent(BtnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BtnBatal)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Kembali)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(55, 55, 55)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(TxtKdPengguna)
                                    .addComponent(TxtUsername)
                                    .addComponent(CbJabatan, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(TxtHP)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(RdLakiLaki)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(RdPerempuan))
                                    .addComponent(TxtNmPengguna)
                                    .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(TxtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, 309, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(35, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtKdPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtNmPengguna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RdPerempuan)
                            .addComponent(RdLakiLaki)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtHP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CbJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(TxtPencarian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BtnSimpan)
                    .addComponent(BtnUpdate)
                    .addComponent(BtnDelete)
                    .addComponent(BtnBatal)
                    .addComponent(Kembali))
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KembaliActionPerformed
    dashboard.FrmDashboard k = new dashboard.FrmDashboard();
        k.setVisible(true);
        this.setVisible(false);        // TODO add your handling code here:
    }//GEN-LAST:event_KembaliActionPerformed
String a;
    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
        // TODO add your handling code here:  
        if(RdLakiLaki.isSelected()){
            a = "Laki-laki";
        }else if(RdPerempuan.isSelected()){
            a = "Perempuan";
        }
            try{                
                st = cn.createStatement();
                st.executeUpdate("insert into tb_user set "+ "kd_pengguna='"+ TxtKdPengguna.getText() +"',"
                        + "nama_pengguna='" + TxtNmPengguna.getText() + "'," 
                        + "jenis_kelamin='" + a +"'," 
                        + "no_hp = '"+TxtHP.getText()+"',"
                        + "jabatan = '"+CbJabatan.getSelectedItem()+"',"
                        + "username = '"+TxtUsername.getText()+"',"
                        + "password='" + TxtPassword.getText() + "'");
                tampilData();
                reset();
                JOptionPane.showMessageDialog(null,"Berhasil Menambah Data!");
            }catch(Exception e){
                e.printStackTrace();
            }
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        // TODO add your handling code here:
        reset();
    }//GEN-LAST:event_BtnBatalActionPerformed

    private void TxtPencarianKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtPencarianKeyReleased
        // TODO add your handling code here:
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("Select * from tb_user where kd_pengguna like '%"+ TxtPencarian.getText() +"%'"
                    + " or nama_pengguna like '%"+ TxtPencarian.getText() +"%' "
                    + "or jabatan like '%"+ TxtPencarian.getText() +"%' "
                    + "or username like '%"+ TxtPencarian.getText() +"%'");
            while(rs.next()){
                Object[] data = {
                    rs.getString("kd_pengguna"),
                    rs.getString("nama_pengguna"),
                    rs.getString("jenis_kelamin"),
                    rs.getString("no_hp"),
                    rs.getString("jabatan"),
                    rs.getString("username"),
                    rs.getString("password")    
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_TxtPencarianKeyReleased

    private void BtnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUpdateActionPerformed
        // TODO add your handling code here:
        if(RdLakiLaki.isSelected()){
            a = "Laki-laki";
        }else if(RdPerempuan.isSelected()){
            a = "Perempuan";
        }
        try{
            st = cn.createStatement();
            st.executeUpdate("update tb_user set "
                +"nama_pengguna='" + TxtNmPengguna.getText() + "',"
                +"jenis_kelamin='" + a + "',"
                +"no_hp='" + TxtHP.getText() + "',"
                +"jabatan='" + CbJabatan.getSelectedItem() + "',"
                +"username='" + TxtUsername.getText() + "',"
                +"password='" + TxtPassword.getText() + "' "
                +"where kd_pengguna='"+ tabModel.getValueAt(TblPengguna.getSelectedRow(),0)+"';");
            tampilData();
            reset();
            JOptionPane.showMessageDialog(null,"Berhasil Mengupdate Data!!");
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnUpdateActionPerformed

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            int jawab;
            if((jawab= JOptionPane.showConfirmDialog(null,"Ingin Menghapus?",
                "Konfirmasi",JOptionPane.YES_NO_OPTION))==0){
        st = cn.createStatement();
        st.executeUpdate("delete from tb_user where "
            + "kd_pengguna='"+ tabModel.getValueAt(TblPengguna.getSelectedRow(),0)+"'");
        tampilData();
        reset();
        JOptionPane.showMessageDialog(null,"Data Telah Terhapus!!");
        }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void TblPenggunaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblPenggunaMouseClicked
        // TODO add your handling code here:
        TxtKdPengguna.setText(tabModel.getValueAt(TblPengguna.getSelectedRow(), 0)+ "");
        TxtNmPengguna.setText(tabModel.getValueAt(TblPengguna.getSelectedRow(), 1)+ "");
        TxtHP.setText(tabModel.getValueAt(TblPengguna.getSelectedRow(), 3)+ "");
        CbJabatan.setSelectedItem(tabModel.getValueAt(TblPengguna.getSelectedRow(), 4)+ "");
        TxtUsername.setText(tabModel.getValueAt(TblPengguna.getSelectedRow(), 5)+ "");
        TxtPassword.setText(tabModel.getValueAt(TblPengguna.getSelectedRow(), 6)+ "");
        BtnSimpan.setEnabled(false);
        BtnUpdate.setEnabled(true);
        BtnDelete.setEnabled(true);
    }//GEN-LAST:event_TblPenggunaMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmPengguna.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmPengguna().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JButton BtnUpdate;
    private javax.swing.JComboBox<String> CbJabatan;
    private javax.swing.JButton Kembali;
    private javax.swing.JRadioButton RdLakiLaki;
    private javax.swing.JRadioButton RdPerempuan;
    private javax.swing.JTable TblPengguna;
    private javax.swing.JTextField TxtHP;
    private javax.swing.JTextField TxtKdPengguna;
    private javax.swing.JTextField TxtNmPengguna;
    private javax.swing.JTextField TxtPassword;
    private javax.swing.JTextField TxtPencarian;
    private javax.swing.JTextField TxtUsername;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
