package dashboard;

import java.*;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.io.InputStream;
import java.io.OutputStream;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.Date;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperExportManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.view.JasperViewer;


public class FrmTransaksi extends javax.swing.JFrame {
    public Statement st;
    public ResultSet rs;
    public DefaultTableModel tabModel;
    Date jdc = new Date();
    Connection cn = koneksi.koneksi.getKoneksi();
     
    public FrmTransaksi() {
        initComponents();
        reset();
        TxtNmBarang.setEnabled(false);
        TxtHarsat.setEnabled(false);
        jDateChooser1.setVisible(false);
        TxtKdTransaksi.setEnabled(false);
        TxtSubTotal.setEnabled(false);
        judul();
        tampilData();
        kode();
        setLocationRelativeTo(this);
        jDateChooser1.setDate(jdc);
    }
    public void judul(){
        Object[] judul = {"Kode Transaksi", "Kode Barang", "Nama Barang",
            "Harga", "Jumlah", "Subtotal",};
        tabModel = new DefaultTableModel(null,judul);
        TblTransaksi.setModel(tabModel);
    }
    
    public void tampilData(){
        try{
            st = cn.createStatement();
            tabModel.getDataVector().removeAllElements();
            tabModel.fireTableDataChanged();
            rs = st.executeQuery("SELECT * FROM tb_keranjang");
            while(rs.next()){
                Object[] data = {
                    rs.getString("kd_transaksi"),
                    rs.getString("kd_barang"),
                    rs.getString("nama_barang"),
                    rs.getString("harga"),
                    rs.getString("jumlah"),
                    rs.getString("subtotal")
                };
                tabModel.addRow(data);
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }
    public void reset(){
        TxtKdBarang.setText("");
        TxtNmBarang.setText("");
        TxtHarsat.setText("");
        TxtJumlah.setText("");
        TxtSubTotal.setText("");
        TxtTotalBayar.setText("");
        TxtJumlahUang.setText("");
        TxtKembalian.setText("");
        TxtTotalBayar.setEnabled(false);
        TxtJumlahUang.setEnabled(false);
        TxtKembalian.setEnabled(false);
        BtnSimpan.setEnabled(true);
        BtnDelete.setEnabled(false);
    }
    public void kode(){
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_transaksi "
                    + "order by kd_transaksi DESC");
            if(rs.next()){
                String kd = rs.getString("kd_transaksi").substring(1);
                String kode = "000" + (Integer.parseInt(kd)+1);
                TxtKdTransaksi.setText("T"+kode);
            }else{
                TxtKdTransaksi.setText("T0001");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal"+e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        TxtNmBarang = new javax.swing.JTextField();
        TxtKdTransaksi = new javax.swing.JTextField();
        BtnSimpan = new javax.swing.JButton();
        BtnBatal = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        TxtHarsat = new javax.swing.JTextField();
        TxtSubTotal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TblTransaksi = new javax.swing.JTable();
        TxtJumlah = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        TxtKdBarang = new javax.swing.JTextField();
        BtnSelesai = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        TxtTotalBayar = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TxtJumlahUang = new javax.swing.JTextField();
        TxtKembalian = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        BtnBayar = new javax.swing.JButton();
        BtnKembali = new javax.swing.JButton();
        BtnDelete = new javax.swing.JButton();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel8.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel8.setText("Sub Total");

        jLabel6.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel6.setText("Harga Satuan");

        TxtNmBarang.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        TxtKdTransaksi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        BtnSimpan.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnSimpan.setText("Simpan");
        BtnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSimpanActionPerformed(evt);
            }
        });

        BtnBatal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnBatal.setText("Batal");
        BtnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBatalActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel7.setText("Jumlah");

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 16)); // NOI18N
        jLabel1.setText("Form Transaksi");

        TxtHarsat.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        TxtSubTotal.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel2.setText("Kode Transaksi");

        TblTransaksi.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TblTransaksi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Kode Transaksi", "Kode Barang", "Nama Barang", "Harga ", "Jumlah"
            }
        ));
        TblTransaksi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TblTransaksiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TblTransaksi);

        TxtJumlah.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TxtJumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtJumlahKeyReleased(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel3.setText("Nama Barang");

        jLabel5.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel5.setText("Kode Barang");

        TxtKdBarang.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TxtKdBarang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtKdBarangKeyReleased(evt);
            }
        });

        BtnSelesai.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnSelesai.setText("Selesai Belanja");
        BtnSelesai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSelesaiActionPerformed(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel4.setText("Total bayar");

        TxtTotalBayar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel9.setText("Jumlah Uang");

        TxtJumlahUang.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        TxtJumlahUang.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                TxtJumlahUangKeyReleased(evt);
            }
        });

        TxtKembalian.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        jLabel10.setText("Kembalian");

        BtnBayar.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnBayar.setText("Bayar");
        BtnBayar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnBayarActionPerformed(evt);
            }
        });

        BtnKembali.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnKembali.setText("Kembali");
        BtnKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnKembaliActionPerformed(evt);
            }
        });

        BtnDelete.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        BtnDelete.setText("Delete");
        BtnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDeleteActionPerformed(evt);
            }
        });

        jDateChooser1.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BtnKembali))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(BtnSimpan))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(TxtKdBarang, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                                        .addComponent(TxtNmBarang)
                                        .addComponent(TxtHarsat)
                                        .addComponent(TxtJumlah))
                                    .addComponent(TxtKdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(TxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addComponent(BtnBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(BtnDelete)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(BtnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel9)
                                    .addComponent(jLabel10))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(TxtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(TxtJumlahUang, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(TxtKembalian, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(18, 18, 18)
                                .addComponent(BtnBayar, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(23, 23, 23))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BtnSelesai, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(TxtTotalBayar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel9)
                                    .addComponent(TxtJumlahUang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel10)
                                    .addComponent(TxtKembalian, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(BtnBayar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(TxtKdTransaksi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(TxtKdBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(TxtNmBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtHarsat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TxtJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(TxtSubTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(BtnSimpan)
                            .addComponent(BtnBatal)
                            .addComponent(BtnDelete))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(BtnKembali)
                .addGap(38, 38, 38))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void BtnKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnKembaliActionPerformed
        dashboard.FrmDashboard k = new dashboard.FrmDashboard();
        k.setVisible(true);
        this.setVisible(false);       
    }//GEN-LAST:event_BtnKembaliActionPerformed

    private void TxtKdBarangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtKdBarangKeyReleased
        // TODO add your handling code here:
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT * FROM tb_barang WHERE kd_barang = "
                    + "'"+TxtKdBarang.getText()+"'");
            if(rs.next()){
                if( TxtKdBarang.getText().equals(rs.getString("kd_barang"))){
                    TxtNmBarang.setText(rs.getString("nama_barang"));
                    TxtHarsat.setText(rs.getString("harga_jual"));
                }
            }else{
                TxtNmBarang.setText("");
                TxtHarsat.setText("");
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal"+e.getMessage());
        }
    }//GEN-LAST:event_TxtKdBarangKeyReleased

    private void TxtJumlahKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJumlahKeyReleased
        // TODO add your handling code here:
        int a,b;
        a = Integer.parseInt(TxtHarsat.getText());
        if(TxtJumlah.getText().equals("")){
            b = 0;
        }else{
            b = Integer.parseInt(TxtJumlah.getText());
        }
        int in_hasil = a*b;
        String hasil = Integer.toString(in_hasil);
        TxtSubTotal.setText(hasil);
    }//GEN-LAST:event_TxtJumlahKeyReleased

    private void BtnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSimpanActionPerformed
            try{                
                st = cn.createStatement();
                st.executeUpdate("insert into tb_keranjang set "
                        + "kd_transaksi='"+ TxtKdTransaksi.getText() +"',"
                        + "kd_barang='" + TxtKdBarang.getText() + "'," 
                        + "nama_barang='" + TxtNmBarang.getText() +"'," 
                        + "harga = '"+TxtHarsat.getText()+"',"
                        + "jumlah = '"+TxtJumlah.getText()+"',"
                        + "subtotal = '"+TxtSubTotal.getText()+"'");
                
                JOptionPane.showMessageDialog(null,"Berhasil Menambah Data!");
            }catch(Exception e){
                e.printStackTrace();
            }
            try{                
                String tgl = ((JTextField)jDateChooser1.getDateEditor()
                        .getUiComponent()).getText();
                st = cn.createStatement();
                st.executeUpdate("insert into tb_transaksi set "
                        + "kd_transaksi='"+ TxtKdTransaksi.getText() +"',"
                        + "kd_barang='" + TxtKdBarang.getText() + "'," 
                        + "nama_barang='" + TxtNmBarang.getText() +"'," 
                        + "harga = '"+TxtHarsat.getText()+"',"
                        + "jumlah = '"+TxtJumlah.getText()+"',"
                        + "subtotal = '"+TxtSubTotal.getText()+"',"
                        + "total = '0',"
                        + "bayar = '0',"
                        + "kembalian = '0',"
                        + "tgl_transaksi='" + tgl + "'");
            }catch(Exception e){
                e.printStackTrace();
            }
            tampilData();
            reset();
    }//GEN-LAST:event_BtnSimpanActionPerformed

    private void BtnBayarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBayarActionPerformed
        // TODO add your handling code here:
            int jawab;
            if((jawab= JOptionPane.showConfirmDialog(null,"Ingin Cetak Struk?",
            "Konfirmasi",JOptionPane.YES_NO_OPTION))==0){
                try{                
                    st = cn.createStatement();
                    st.executeUpdate("update tb_transaksi set "
                            + "total = '"+TxtTotalBayar.getText()+"',"
                            + "bayar = '"+TxtJumlahUang.getText()+"',"
                            + "kembalian = '"+TxtKembalian.getText()+"'"
                            + "WHERE kd_transaksi='"+ TxtKdTransaksi.getText() +"'");
                    Class.forName("com.mysql.jdbc.Driver");
                    cn = DriverManager.getConnection("jdbc:mysql://localhost/db_gshop","root","");
                    InputStream in = new FileInputStream(new File 
                    ("E:\\Project\\Java\\AplikasiPOS\\src\\laporan\\FakturTransaksi.jrxml"));
                    JasperDesign jd =JRXmlLoader.load(in);
                    String sql = "SELECT * FROM query_faktur WHERE kd_transaksi = '"+TxtKdTransaksi.getText()+"'";
                    JRDesignQuery newQuery = new JRDesignQuery();
                    newQuery.setText(sql);
                    jd.setQuery(newQuery);
                    JasperReport jr =JasperCompileManager.compileReport(jd);
                    HashMap para = new HashMap();
                    JasperPrint j = JasperFillManager.fillReport(jr,para,cn);
                    JasperViewer.viewReport(j,false);
                    OutputStream os =new FileOutputStream(new File("E:\\Project\\Java\\Report"));
                    JasperExportManager.exportReportToPdfStream(j, os);
                }catch(Exception e){
                    e.printStackTrace();
                }
                try{
                    st = cn.createStatement();
                    st.executeUpdate("TRUNCATE TABLE tb_keranjang");
                    tampilData();
                    reset();
                }catch(Exception e){
                    e.printStackTrace();
                }
            }else{  
                try{                
                    st = cn.createStatement();
                    st.executeUpdate("update tb_transaksi set "
                            + "total = '"+TxtTotalBayar.getText()+"',"
                            + "bayar = '"+TxtJumlahUang.getText()+"',"
                            + "kembalian = '"+TxtKembalian.getText()+"'"
                            + "WHERE kd_transaksi='"+ TxtKdTransaksi.getText() +"'");
                    try{
                        st = cn.createStatement();
                        st.executeUpdate("TRUNCATE TABLE tb_keranjang");
                        tampilData();
                        reset();
                    }catch(Exception e){
                        e.printStackTrace();
                    }
                }catch(Exception e){
                    e.printStackTrace();
                }
            }
            reset();
            kode();
    }//GEN-LAST:event_BtnBayarActionPerformed

    private void BtnSelesaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSelesaiActionPerformed
        // TODO add your handling code here:
        try{
            st = cn.createStatement();
            rs = st.executeQuery("SELECT SUM(subtotal) FROM tb_keranjang ");
            if(rs.next()){
                  TxtJumlahUang.setEnabled(true);
                  TxtTotalBayar.setText(rs.getString(1));
            }
        }catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Koneksi gagal"+e.getMessage());
        }
    }//GEN-LAST:event_BtnSelesaiActionPerformed

    private void TxtJumlahUangKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtJumlahUangKeyReleased
        // TODO add your handling code here:
        int a,b;
        a = Integer.parseInt(TxtTotalBayar.getText());
        if(TxtJumlahUang.getText().equals("")){
            b = 0;
        }else{
            b = Integer.parseInt(TxtJumlahUang.getText());
        }
        int in_hasil = b-a;
        String hasil = Integer.toString(in_hasil);
        TxtKembalian.setText(hasil);
    }//GEN-LAST:event_TxtJumlahUangKeyReleased

    private void BtnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDeleteActionPerformed
        // TODO add your handling code here:
        try{
            int jawab;
            if((jawab= JOptionPane.showConfirmDialog(null,"Ingin Menghapus?",
                "Konfirmasi",JOptionPane.YES_NO_OPTION))==0){
                st = cn.createStatement();
                st.executeUpdate("delete from tb_transaksi where "
                    + "kd_transaksi='"+ tabModel.getValueAt(TblTransaksi.getSelectedRow(),0)+"'");               
                try{
                    st = cn.createStatement();
                    st.executeUpdate("delete from tb_keranjang where "
                    + "kd_transaksi='"+ tabModel.getValueAt(TblTransaksi.getSelectedRow(),0)+"'");
                }catch(Exception e){
                    e.printStackTrace();
                }
                JOptionPane.showMessageDialog(null,"Data Telah Terhapus!!");
                tampilData();
                reset();
            }
        }catch(Exception e){
            e.printStackTrace();
        }
    }//GEN-LAST:event_BtnDeleteActionPerformed

    private void TblTransaksiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TblTransaksiMouseClicked
        // TODO add your handling code here:
        TxtKdTransaksi.setText(tabModel.getValueAt(TblTransaksi.getSelectedRow(), 0)+ "");
        BtnSimpan.setEnabled(false);
        BtnDelete.setEnabled(true);
    }//GEN-LAST:event_TblTransaksiMouseClicked

    private void BtnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnBatalActionPerformed
        // TODO add your handling code here:
        reset();
        kode();
    }//GEN-LAST:event_BtnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmTransaksi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmTransaksi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnBatal;
    private javax.swing.JButton BtnBayar;
    private javax.swing.JButton BtnDelete;
    private javax.swing.JButton BtnKembali;
    private javax.swing.JButton BtnSelesai;
    private javax.swing.JButton BtnSimpan;
    private javax.swing.JTable TblTransaksi;
    private javax.swing.JTextField TxtHarsat;
    private javax.swing.JTextField TxtJumlah;
    private javax.swing.JTextField TxtJumlahUang;
    private javax.swing.JTextField TxtKdBarang;
    private javax.swing.JTextField TxtKdTransaksi;
    private javax.swing.JTextField TxtKembalian;
    private javax.swing.JTextField TxtNmBarang;
    private javax.swing.JTextField TxtSubTotal;
    private javax.swing.JTextField TxtTotalBayar;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
